### ISSUE TITLE
Error in browser console (n is undefined)

### ISSUE THREAD

**Issue by furious-luke** [ag91/code-compass#2]
Hi there! I'm in the process of trying out code-compass, and I'm finding that I see the following error in the browser:

![image](https://user-images.githubusercontent.com/561722/103600623-fb336600-4f5b-11eb-8af7-c19d3bd80ccb.png)

The page itself is blank. To get to that result I opened one of my repositories, and ran `M-x c/show-hotspots`. No errors are reported in emacs.

**Comment by BlankSpruce** [comment]
It matches my experience when `python` is not pointing to `python2`. I've tested it with [gersemi](https://github.com/BlankSpruce/gersemi). Here's what happens in Firefox:
![image](https://user-images.githubusercontent.com/32396809/103667839-b49f3500-4f76-11eb-863a-147c0590404a.png)
and Chromium:
![image](https://user-images.githubusercontent.com/32396809/103667883-c385e780-4f76-11eb-8eee-20e9e2690492.png)

However if you apply this patch it works as expected:
```diff
diff --git a/code-compass.el b/code-compass.el
index 9b210d7..af12d2a 100644
--- a/code-compass.el
+++ b/code-compass.el
@@ -2936,7 +2936,7 @@ ZHVsZSYmbW9kdWxlLmV4cG9ydHM/bW9kdWxlLmV4cG9ydHM9R286dGhpcy5kMz1Hb30oK
TsK"                                                                                      
   (message "Produce json...")
   (shell-command
    (format
-    "cd /tmp; python csv_as_enclosure_json.py --structure cloc-%s.csv --weights %s-revisio
ns.csv > /tmp/%s/%s_hotspot_proto.json"                                                   
+    "cd /tmp; python2 csv_as_enclosure_json.py --structure cloc-%s.csv --weights %s-revisi
ons.csv > /tmp/%s/%s_hotspot_proto.json"                                                  
     (f-filename repository)
     (f-filename repository)
     (f-filename repository)
```

**Comment by furious-luke** [comment]
@ag91 Thanks for the quick response, much appreciated. I think @BlankSpruce has identified the issue; I'm using Python 3.8 by default, and so it's most likely the same issue. I'll try the patch and see how it goes. Thanks!

**Comment by furious-luke** [comment]
Yep, that resolves the issue. Thanks @BlankSpruce, much appreciated!

**Comment by davidkrauser** [comment]
I'm seeing this same issue (n is undefined) with the latest main branch (58daee0), but it looks like @BlankSpruce 's patch no longer applies :-/

I tried @BlankSpruce 's branch (https://github.com/ag91/code-compass/pull/5/commits/803e920aecdf8fd5b923484264a706a3cbfcc2c3) from an open pull request that appeared to be d3 related, but that just moved the problem. Now I see:

```
Uncaught TypeError: i is undefined
    n http://localhost:8888/d3/d3.v3.min.js:4
    n http://localhost:8888/d3/d3.v3.min.js:4
    <anonymous> http://localhost:8888/script.js:45
    t http://localhost:8888/d3/d3.v3.min.js:1
    i http://localhost:8888/d3/d3.v3.min.js:1
    Cn http://localhost:8888/d3/d3.v3.min.js:1
    json http://localhost:8888/d3/d3.v3.min.js:5
    <anonymous> http://localhost:8888/script.js:43
d3.v3.min.js:4:23546
```

This is happens when running `c/show-knowledge-graph` on Debian Unstable with Python 3.9 and Emacs 27.1. Other commands have similar results.

**Comment by ag91** [comment]
I will try to reproduce asap. At the moment I do not have 3.9 yet, so could you run the failing analysis (knowledge for example) and then move to /tmp/code-compass-<your-project> and run `python3 knowledge_csv_as_enclosure_diagram.py --structure cloc.csv --owners main-dev.csv --authors authors.csv`?
It would help me to know if you see a result or not that looks like json (I do not need the output because it contains data about your repository that you may not want to share).

**Comment by BlankSpruce** [comment]
The closest I could get to reproducing this problem was when I removed `code-maat` from the system:
![image](https://user-images.githubusercontent.com/32396809/107283095-3560bd80-6a5c-11eb-86a9-12401e8a1046.png)

Steps:
1) Build the following Dockerfile:
```
FROM debian:unstable

RUN \
        apt update \
        && apt install -y emacs git python3 cloc \
        && cd ~ \
        && git clone https://github.com/ag91/code-compass

ENTRYPOINT ["/usr/bin/emacs"]
```

2a) Inside dockerized emacs install all the elisp dependencies of `code-compass` (minimal setup example is helpful).
```
docker build -t code-compass-reproduce-issue .
docker run -v /tmp/:/tmp/ -it code-compass-reproduce-issue
```
2b) As a cheat step you can use `.emacs.d` from the host but you have to open dockerized emacs like so:
```
docker run -v /tmp/:/tmp/ -v ~/.emacs.d/:/root/.emacs.d/ -it code-compass-reproduce-issue
```
3) Invoke `c/show-knowledge-graph` on `code-compass` itself (since it's available inside the image).
4) Open produced `/tmp/code-compass-code-compass/zoomable.html`.

Since inside the image there is no code-maat `main-dev.csv` file is empty which then leads to this error:
```
$ python3 knowledge_csv_as_enclosure_diagram.py --structure cloc.csv --owners main-dev.csv --authors authors.csv
Traceback (most recent call last):
  File "/tmp/code-compass-code-compass/knowledge_csv_as_enclosure_diagram.py", line 183, in <module>
    run(args)
  File "/tmp/code-compass-code-compass/knowledge_csv_as_enclosure_diagram.py", line 166, in run
    module_ownership = parse_csv(args.owners,
  File "/tmp/code-compass-code-compass/knowledge_csv_as_enclosure_diagram.py", line 40, in parse_csv
    heading = read_heading_from(r)
  File "/tmp/code-compass-code-compass/knowledge_csv_as_enclosure_diagram.py", line 34, in read_heading_from
    p = next(r)
StopIteration
```

@davidkrauser 
Double check if you have code-maat installed. Given that `c/code-maat-command` by default is set to dockerized code-maat you should see something like this:
```
$ docker run -it code-maat-app --help   
This is Code Maat, a program used to collect statistics from a VCS.
Version: 1.0-SNAPSHOT

[...rest of the output...]
```
If code-maat is available please confirm if `/tmp/code-compass-<your-project>/main-dev.csv` is empty.

**Comment by davidkrauser** [comment]
@BlankSpruce that was the issue - code-maat was installed but emacs had permissions issues interacting with docker. Thank you, everything appears to be working as expected now. Strange that this manifested in almost the same way as an unrelated issue. /cc @ag91

**Comment by ag91** [comment]
great way to reproduce @BlankSpruce: smart idea to use Docker!
@davidkrauser would you mind to share here how you fixed the permission issue (in case somebody else struggles with it later)?

**Comment by davidkrauser** [comment]
@ag91 absolutely - I added myself to the docker group (`sudo usermod -aG docker $USER`), but I didn't log out/log in to get that to stick in all environments. I used `newgrp docker` in my terminal to ensure code-maat worked in the terminal. Unfortunately, Emacs (and the subprocesses it spawned) didn't recognize that I had been added to the docker group. Logging out and logging back in fixed my problem.

**Comment by ag91** [comment]
Very clear explanation! Thanks David and let's hope it was just a quirk.

**Comment by mattford63** [comment]
Hi, I see this issue when trying to view hotspot analysis

(as an aside I also see CORS related issues on later browsers
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp
)

**Comment by mattford63** [comment]
You end up with this error message if you don't satisfy any of the dependencies required - in my case it was `cloc`.  Perhaps a do we meet requirements function would help solve this?

**Comment by ag91** [comment]
Thanks @mattford63 for reminding me: I was planning to write a c/doctor from a while: I have now added it. Sorry for your waste of time, I should have spent a few minutes on this earlier on. Added it now: better later than never.
