### ISSUE TITLE
Extend Hashmap on cache load instead of overwritting

### ISSUE THREAD

**Issue by gopar** [ag91/code-compass#38]
Just realized I didn't think something through.

Right now, caching works by overwritting `code-compass-coupling-project-map` with whatever is in the cache.

This isn't ideal, it would be better preferred if it extended the current hashmap instead.

Reasoning:
1.  Working on Project X
2. Run command to get coupled files, so `code-compass-coupling-project-map` is now populated.
3. Go to Project Y
4. Run command to get coupled files, (we see cache exists for this project so we overwrite `code-compass-coupling-project-map`, hence loosing all previous coupling info for Project X)

**Comment by ag91** [comment]
mmm, I tried and I don't get that result: I designed `code-compass-couplding-project-map` to add the coupling of a project by the repository path.
So each time you cache the map, you get a map repository -> coupled files.
There is indeed an issue though: the caching now creates a file with the branch hash, but which contains the whole map.
Let me fix this because re-reading the code, I found out I already planned to do something similar with code-compass-calculate-coupling-project-key-fn`, which by default is `identity` but for the feature you implemented should have been repo+hash. 
That way we don't need to store a new file every time, but just update the cache every time we regenerate it.
Anyway, gonna fix this other error soon.

Please let me know if you manage to reproduce the error you meant.
